### ISSUE TITLE
Exit code non zero

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/node-core-utils#130]
I think it would be nice if the call would return a non-zero exit code in case a requirement is missing.

**Comment by cPhost** [comment]
Sure, do you want to make a PR it just adding non-zero exit if status is false.

**Comment by ryzokuken** [comment]
@BridgeAR @cPhost I'd love to have a shot at this one, I'd just need a little more detail regarding what exactly needs to be done.

**Comment by joyeecheung** [comment]
I think this has been fixed now? AFAICT, the commands are using `runPromise` to run things and that exits with 1 in `.catch` (which reminded me there seem to be another bug...all the `.catch` attached to `runPromise` or `runAsync` calls will not be called because of that)

**Comment by ryzokuken** [comment]
@joyeecheung If you're positive about it, please proceed to close this issue. Also, let me know if you think the redundant `.catch` calls should be removed, and I'll look into it.

**Comment by cPhost** [comment]
This is still not fixed yet, all that needs to be done is, add a `then` to `getMetadata` and if the status if false exit with non-zero exit code.

**Comment by ryzokuken** [comment]
@cPhost isn't `get-metadata` deprecated?
